# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to=rent.models.itemuploadpath)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('reward', models.CharField(blank=True, max_length=100)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('borrower_note', models.TextField(blank=True, max_length=300)),
                ('reward', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(blank=True, null=True, upload_to=rent.models.useruploadpath)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to=rent.models.itemuploadpath)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('reward', models.CharField(blank=True, max_length=100, null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('need_from', models.DateField(blank=True, null=True)),
                ('need_to', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('lender_note', models.TextField(blank=True, max_length=300)),
                ('reward', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.RequestingItem')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responding_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.OfferingItem')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offer', models.BooleanField()),
                ('reward', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('review_to_lender', models.TextField(blank=True, max_length=300, null=True)),
                ('review_to_borrower', models.TextField(blank=True, max_length=300, null=True)),
                ('rate_to_lender', models.IntegerField(blank=True, default=5)),
                ('rate_to_borrower', models.IntegerField(blank=True, default=5)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_borrow', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lend', to=settings.AUTH_USER_MODEL)),
                ('offer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.OfferingItem')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.RequestingItem')),
            ],
        ),
        migrations.AddField(
            model_name='offerresponse',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.OfferingItem'),
        ),
        migrations.AddField(
            model_name='offeringitem',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
