# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeringitem',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeringitem',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerresponse',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerresponse',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestingitem',
            name='need_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestingitem',
            name='need_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
