# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20170430_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestingitem',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
